# Instructions
# 1. Clone the repo
# 2. Change the name of the pod and the PVC claim name
# 3. Create the pod 
# 4. Port forward the pod to your local machine, 8888:8888
# 5. Open your browser and go to localhost:8888
# 6. Enter the token from the pod logs

apiVersion: v1
kind: Pod
metadata:
  name: jonathan-jupyter-notebook
spec:
  containers:
  - name: jonathan-jupyter-notebook
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
    command: ["sh", "-c", "sudo apt-get update && pip3 install torch torchvision torchaudio && jupyter notebook --ip='0.0.0.0' && sleep infinity"]
    resources:
      limits:
        memory: 20Gi
        cpu: "16"
        nvidia.com/gpu: 1
      requests:
        memory: 2Gi
        cpu: "2"
        nvidia.com/gpu: 1

        # Uncomment Section to mount a PVC

        #   volumeMounts:
        #   - mountPath: /pvcvolume
        #     name: pvc
        # restartPolicy: Never
        # volumes:
        # - name: pvc
        #   persistentVolumeClaim:
        #     claimName: j-carla
