apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jonathan-video-classification
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
