apiVersion: v1
kind: Pod
metadata:
  name: jonathan-pod-2
spec:
  containers:
  - name: test-pod
    image: pytorch/pytorch
    resources:
      limits:
        memory: 20Gi
        cpu: 10
        nvidia.com/gpu: 1
      requests:
        memory: 5Gi
        cpu: 5
        nvidia.com/gpu: 1
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    volumeMounts:
    - mountPath: /pvcvolume
      name: examplevol
  volumes:
  - name: examplevol
    persistentVolumeClaim:
      claimName: sample-dataset-2
