apiVersion: apps/v1
kind: Deployment
metadata:
  name: j-desktop-2
  labels:
    k8s-app: j-desktop-2-2
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: j-desktop-2
  template:
    metadata:
      labels:
        k8s-app: j-desktop-2
    spec:
      containers:
      - name: j-desktop-2
        image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04
        resources:
          limits:
            memory: 20Gi
            cpu: "10"
            nvidia.com/gpu: 1
            ephemeral-storage: 500Gi
          requests:
            memory: 20Gi
            cpu: "5"
            nvidia.com/gpu: 1
            ephemeral-storage: 500Gi
        command: ["sh", "-c", "sleep infinity"]
        volumeMounts:
        - mountPath: /pvcvolume
          name: examplevol
      volumes:
      - name: examplevol
        persistentVolumeClaim:
          claimName: j-2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-L40
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/gilpin-lab
        operator: Exists
