apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jonathan-autogen
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
