apiVersion: apps/v1
kind: Deployment
metadata:
  name: jonathan-snn
  labels:
    k8s-app: jonathan-snn
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jonathan-snn
  template:
    metadata:
      labels:
        k8s-app: jonathan-snn
    spec:
      containers:
      - name: jonathan-snn
        image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04
        resources:
          limits:
            memory: 5Gi
            cpu: "10"
            nvidia.com/gpu: 1
            # ephemeral-storage: 500Gi
          requests:
            memory: 5Gi
            cpu: "2"
            nvidia.com/gpu: 1
            # ephemeral-storage: 500Gi
        command: [ "sh", "-c", "sleep infinity" ]
      #   volumeMounts:
      #   - mountPath: /pvcvolume
      #     name: examplevol
      # volumes:
      # - name: examplevol
      #   persistentVolumeClaim:
      #     claimName: jonathan-snn
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: nvidia.com/gpu.product
      #           operator: In
      #           values:
      #           - NVIDIA-A100-80GB-PCIe
      # tolerations:
      # - effect: NoSchedule
      #   key: nautilus.io/gilpin-lab
      #   operator: Exists
