# Strat -> find and replace "jonathan-video-classification" with whatever you want and then add enable features as needed
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jonathan-video-classification
  labels:
    k8s-app: jonathan-video-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jonathan-video-classification
  template:
    metadata:
      labels:
        k8s-app: jonathan-video-classification
    spec:
      containers:
      - name: jonathan-video-classification
        image: nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
        resources:
          limits:
            memory: 32Gi
            cpu: "10"
            nvidia.com/gpu: 1
          requests:
            memory: 32Gi
            cpu: "10"
            nvidia.com/gpu: 1
        command: [ "sh", "-c", "sleep infinity" ]
        volumeMounts:
        - mountPath: /pvcvolume
          name: examplevol
      volumes:
      - name: examplevol
        persistentVolumeClaim:
          claimName: jonathan-video-classification
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
      # tolerations:
      # - effect: NoSchedule
      #   key: nautilus.io/gilpin-lab
      #   operator: Exists
