apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cruzid-carla-cache # Change this to your cruzid
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
