apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cruzid-carla # Change this to your cruzid
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
